services:
  postgres:
    image: postgres:17
    container_name: petshop-planner-db
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=petshop_planner
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
